ci:
  autofix_prs: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff-format
        args: ["--diff", "src", "tests"]
      - id: ruff
        args: ["--select", "I", "src", "tests"]

  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.2
    hooks:
      - id: doc8
        additional_dependencies:
          - toml

  # Removing since aristaproto don't use the java code and this breaks CI.
  # - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  #   rev: v2.10.0
  #   hooks:
  #     - id: pretty-format-java
  #       args: [--autofix, --aosp]
  #       files: ^.*\.java$
